<?php

namespace AppBundle\Api;

use Symfony\Component\HttpKernel\Exception\HttpException;
use AppBundle\Api\ApiProblem;

class ApiProblemException extends HttpException
{
    private $apiProblem;

    public function __construct(ApiProblem $apiProblem, \Exception $previous = null, array $headers = array(), $code = 0)
    {
        $this->apiProblem = $apiProblem;
        $statusCode = $apiProblem->getStatusCode();
        $message = $apiProblem->getTitle();

        parent::__construct($statusCode,$message,$previous,$headers,$code); // TODO: Change the autogenerated stub

    }

    /**
     * @return \AppBundle\Api\ApiProblem
     */
    public function getApiProblem() {
        return $this->apiProblem;
    }
}
